import 'dart:convert';
import 'dart:ui';

import 'package:flutter/foundation.dart';

import 'package:flutter_cache/flutter_cache.dart' as cache;
import 'package:xta/client/accounts.dart';
import 'package:xta/client/headers.dart';
import 'package:http/http.dart' as http;
import 'package:logging/logging.dart';

/// How long a translated post is kept. The key names a single post, so without
/// an expiry the cache grows with every post ever translated and is never
/// pruned.
const Duration translationCacheTtl = Duration(days: 7);

/// Cache key for one translation.
///
/// The target locale is part of the key. It used to be absent, which was
/// harmless only because the cache was never read — see
/// [decodeCachedTranslation]. Repairing the read without this would have served
/// a reader who changed their device language the translation from the old one.
String translationCacheKey({required String id, required String sourceLanguage, required Locale target}) =>
    'translation.$sourceLanguage.${target.toLanguageTag()}.$id';

/// A cached translation, or null when there is nothing usable stored.
///
/// The guard here used to read `result != null && result == true`, comparing
/// the cached *string* against a bool. That is always false, so the cache was
/// written on every translation and read on none: each one re-requested from X
/// while the entries accumulated on disk, unread.
TranslationAPIResult? decodeCachedTranslation(Object? cached) {
  if (cached is! String || cached.isEmpty) {
    return null;
  }
  try {
    return TranslationAPIResult(success: true, body: jsonDecode(cached));
  } on FormatException {
    // Written by an older build, or truncated. Re-requesting is correct.
    return null;
  }
}

class TranslationAPIResult {
  final bool success;
  final dynamic body;
  final String? errorMessage;

  TranslationAPIResult({required this.success, required this.body, this.errorMessage});
}

// TODO
class TranslationAPI {
  static final log = Logger('TranslationAPI');

  static Future<TranslationAPIResult> translate(
      Locale locale, String id, List<String> text, String sourceLanguage) async {
    var formData = {'id': id, 'dst_lang': locale.toLanguageTag(), 'content_type': 'POST'};

    var key = translationCacheKey(id: id, sourceLanguage: sourceLanguage, target: locale);

    var res = await cacheRequest(key, () async {
      Future<http.Response> getTranslation() async {
        final translationUri = Uri.https('api.x.com', '/2/grok/translation.json');
        return await http.post(translationUri, body: jsonEncode(formData), headers: {
          ...await TwitterHeaders.getHeaders(translationUri, await pickAuthHeader()),
          'Content-Type': 'text/plain;charset=UTF-8',
          'Accept-Encoding': 'gzip, deflate, br, zstd'
        });
      }

      const int numberOfRetries = 3;

      for (int i = 0; i < numberOfRetries; ++i) {
        try {
          return await parseResponse(await getTranslation(), 'Unable to send translation request');
        } on FormatException {
          // Wait a bit while the translation is fully generated by Grok
          await Future.delayed(Duration(seconds: 1));
        }
      }
      return TranslationAPIResult(success: false, body: {}, errorMessage: "Translation is not ready yet, retry later.");
    });

    return res;
  }

  static Future<TranslationAPIResult> cacheRequest(
      String key, Future<TranslationAPIResult> Function() makeRequest) async {
    final cached = decodeCachedTranslation(await cache.load(key));
    if (cached != null) {
      return cached;
    }

    final response = await makeRequest();
    if (response.success) {
      // Only successes are cached, and only for a while: the key names one post,
      // so an unbounded cache grows with every post ever translated.
      await cache.write(key, jsonEncode(response.body), translationCacheTtl.inSeconds);
    }

    return response;
  }

  static Future<TranslationAPIResult> parseResponse(http.Response response, String errorUnableTo) async {
    final utf8Response = utf8.decode(response.bodyBytes);
    final body = jsonDecode(utf8Response);
    log.info("Translation result: $body");
    if (response.statusCode == 200 && body is Map<String, dynamic>) {
      if (body.containsKey("error")){
        var error = body['error'];
        return TranslationAPIResult(success: false, body: body, errorMessage: error['message'] ?? error['code'] ?? '');
      }
      return TranslationAPIResult(success: true, body: body);
    }

    String message = '';

    switch (response.statusCode) {
      case 400:
        RegExp languageNotSupported = RegExp(r"^\w+ is not supported$");

        var error = body['error'];
        if (languageNotSupported.hasMatch(error)) {
          message = 'Language $error';
        } else {
          message = error;
        }
        break;
      case 403:
        message = 'Error: Banned from translation API';
        break;
      case 429:
        message = 'Error: Sending too many frequent translation requests';
        break;
      case 500:
        message = 'Error: The translation API failed to translate the tweet';
        break;
    }

    return TranslationAPIResult(success: false, body: body, errorMessage: message);
  }
}

/// Lets one tweet's translate button request translation of every tweet
/// currently shown in the same provider scope (e.g. a whole conversation).
class TranslationBroadcast extends ChangeNotifier {
  void requestAll() => notifyListeners();
}
